export const COMPONENT_ID = 'COMPONENT_ID';
export const GET_TIMESHEET_TYPES = 'GET_TIMESHEETS';
export const TIMESHEET_SET_DATA = 'STORE_TIMESHEETS';

export const GET_TIMESHEET_DATA = 'GET_TIMESHEET_DATA'
export const LOADING_TIMESHEET_DATA = 'LOADING_TIMESHEET_DATA'
export const ERROR_TIMESHEET_DATA = 'ERROR_TIMESHEET_DATA'

export const SUBMIT_TIMESHEET_DATA = 'SUBMIT_TIMESHEET_DATA'
export const SUBMIT_TIMESHEET_DATA_ERROR = 'SUBMIT_TIMESHEET_DATA_ERROR'
export const SUBMIT_TIMESHEET_DATA_LOADING = 'SUBMIT_TIMESHEET_DATA_LOADING'

export const GET_TIMESHEET_DATA_PARTICULAR_RANGE = 'GET_TIMESHEET_DATA_PARTICULAR_RANGE';
export const LOGIN_ROUTE = "/Login";
export const GET_SHEET_ROUTE = "/TimeSheet/GetTimeSheets";
export const ADD_SHEET_ROUTE = "/TimeSheet/AddTimeSheet";
export const EDIT_SHEET_ROUTE = "/TimeSheet/EditTimeSheets";
export const PICKER_ROUTE = "/PickerRecords";
